stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  tags:
    - shell
  script:
    - docker compose -f docker-compose.test.yml build

test-backend-job:
  stage: test
  tags:
    - shell
  script:
    - docker compose -f docker-compose.test.yml up -d postgres
    - docker compose -f docker-compose.test.yml run --rm backend npm run test:ci
  after_script:
    - docker compose -f docker-compose.test.yml down -v

deploy-job:
  stage: deploy
  tags:
    - shell
  script:
    # 1. Останавливаем старые контейнеры
    - docker compose down --remove-orphans || true
    
    # 2. Обновляем конфиг системного nginx
    - sudo cp nginx/foodtracker.conf /etc/nginx/sites-available/foodtracker
    - sudo nginx -t && sudo systemctl restart nginx
    
    # 3. Запускаем новые контейнеры
    - docker compose up -d --build
  only:
    - main