stages:
  - build
  - test
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"

default:
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind

build-job:
  stage: build
  script:
    # Собираем все образы локально для тестирования
    - docker compose -f docker-compose.test.yml build

test-backend-job:
  stage: test
  script:
    # 1. Запускаем базу данных и ждем ее готовности
    - docker compose -f docker-compose.test.yml up -d postgres
    # 2. Запускаем тесты бэкенда (юнит / интеграционные API) прямо в контейнере бэкенда
    - docker compose -f docker-compose.test.yml run --rm backend npm run test:ci
  after_script:
    - docker compose -f docker-compose.test.yml down

test-e2e-job:
  stage: test
  script:
    - echo "File contents:"
    - cat "$TEST_ENV_FILE"
    - cp "$TEST_ENV_FILE" .env
    - echo "Copied .env contents:"
    - cat .env
    - docker compose -f docker-compose.test.yml up -d nginx
    - sleep 10
    - docker compose -f docker-compose.test.yml run --rm e2e-tests
  after_script:
    # Обязательно очищаем окружение после тестов
    - docker compose -f docker-compose.test.yml down -v
  artifacts:
    # Сохраняем скриншоты и видео ошибок, если тесты упали
    when: on_failure
    paths:
      - e2e/playwright-report/
    expire_in: 1 week

deploy-job:
  stage: deploy
  script:
    - docker compose up -d
