services:
  postgres:
    image: postgres:16-alpine
    container_name: foodtracker-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d foodtracker" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: foodtracker-api
    restart: unless-stopped
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432 
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      PORT: 3000
      NODE_ENV: production
      FATSECRET_CLIENT_ID: ${FATSECRET_CLIENT_ID}
      FATSECRET_CLIENT_SECRET: ${FATSECRET_CLIENT_SECRET}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy # ждём, пока БД не станет готова

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: foodtracker-web
    restart: unless-stopped
    depends_on:
      - backend
    
      
  nginx:
    build:
      context: ./nginx
      dockerfile: nginx/Dockerfile
    container_name: foodtracker-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata: # именованный том — данные БД сохранятся при пересборке
