version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: test
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile

  nginx:
    image: nginx:alpine
    volumes:
      -  ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  # e2e-tests:
  #   image: mcr.microsoft.com/playwright:v1.52.0-noble
  #   environment:
  #     - BASE_URL=http://nginx # Тесты ходят через NGINX
  #   working_dir: /e2e 
  #   volumes:
  #     - ./e2e:/e2e
  #   command: npx playwright test
  #   depends_on:
  #     - nginx
