services:
  postgres:
    image: postgres:16-alpine
    container_name: foodtracker-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    # volumes:
    #   - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d foodtracker"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: foodtracker-api-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: 3000
      NODE_ENV: development
      FATSECRET_CLIENT_ID: ${FATSECRET_CLIENT_ID}
      FATSECRET_CLIENT_SECRET: ${FATSECRET_CLIENT_SECRET}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
      GROQ_API_KEY: ${GROQ_API_KEY}
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: foodtracker-web-dev
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  pgdata_dev: